spring.application.name=api-gateway
management.tracing.sampling.probability=1.0

logging.file.name=logs/app.log




management.tracing.zipkin.endpoint=http://zipkin:9411/api/v2/spans

# Make Zipkin non-blocking and fast-fail
management.zipkin.tracing.connect-timeout=500
management.zipkin.tracing.read-timeout=500
management.zipkin.tracing.write-timeout=500

# Reduce span batch size (prevents blocking)
management.zipkin.tracing.encoder=json_v2
management.tracing.enabled=false