apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: order-service:latest
          ports:
            - containerPort: 8083
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker

            # Database
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://host.docker.internal:3306/foodservice
            - name: SPRING_DATASOURCE_USERNAME
              value: root
            - name: SPRING_DATASOURCE_PASSWORD
              value: Shashank@2530

            # Kafka
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: host.docker.internal:9092

          resources:
            requests:
              cpu: 100m
            limits:
              cpu: 200m