spring.application.name=order-service
server.port=8083

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.datasource.url=jdbc:mysql://mysql:3306/foodservice
#spring.datasource.username=root
#spring.datasource.password=Shashank@2530
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

logging.file.name=/app/logs/app.log

#spring.zipkin.base-url=http://zipkin:9411
spring.zipkin.base-url=${ZIPKIN_BASE_URL}
#management.zipkin.tracing.endpoint=http://zipkin:9411/api/v2/spans
management.zipkin.tracing.endpoint=${ZIPKIN_ENDPOINT}
management.tracing.sampling.probability=1.0
